In [3]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
import scipy.spatial.distance as spd
import numpy.linalg as lg
from scipy.linalg import sqrtm

In [4]:
#Pergunta 1 a)
w1 = np.array([[-4,-3],[-2,-2],[-5,1],[-3,-2]])
X = w1.T
CxReal = np.cov(X)
print("CxReal")
print(CxReal)
print()
#i) RESPOSTA V
print("Matrix Teste 1")
print(np.cov(X,ddof=1))
print()

#ii)RESPOSTA F
mx=np.mean(X,axis=1)
Xn=(X.T-mx).T
Ctmp=Xn*Xn
print("Matrix Teste 2")
print(Ctmp/(w1.shape[1]-1))
print()


#iii) RESPOSTA F
print("Matrix teste 3")
print(np.cov(X.T,rowvar=False,ddof=0))
print()

#iv) RESPOSTA F
mx=np.mean(X,axis=0)
Xn=X-mx
Ctmp=np.dot(Xn,Xn.T)
print("Matrix teste 4")
print(Ctmp/(X.shape[1]-1))

CxReal
[[ 1.66666667 -1.33333333]
 [-1.33333333  3.        ]]

Matrix Teste 1
[[ 1.66666667 -1.33333333]
 [-1.33333333  3.        ]]

Matrix Teste 2
[[0.25 2.25 2.25 0.25]
 [2.25 0.25 6.25 0.25]]

Matrix teste 3
[[ 1.25 -1.  ]
 [-1.    2.25]]

Matrix teste 4
[[ 3.16666667 -3.16666667]
 [-3.16666667  3.16666667]]


In [5]:
#Perunta 1 b)
#i)RESPOTA V
A=np.array([[8.53,0.87],[0.87,7.52]])
m=np.array([1, 2])
Y=np.dot(A,X)+m[:,np.newaxis]
print(Y)
print()
#ii)RESPOSTA V
Cy=np.array([[73.56,13.92],[13.92,57.34]])
A=sqrtm(Cy)
m=np.array([1, 2])
Y=np.dot(A,X)+m[:,np.newaxis]
print(Y)

#iii) RESPOSTA V

#iv) RESPOSTA F


[[-35.73 -17.8  -40.78 -26.33]
 [-24.04 -14.78   5.17 -15.65]]

[[-35.73212362 -17.79956357 -40.7968878  -26.33234183]
 [-24.03557364 -14.77904674   5.18750224 -15.64605026]]


In [6]:
#Pergunta 2 a) 
#i) RESPOSTA F
w0 = np.array([[-4,-3],[-2,-2],[-5,1],[-3,-2]])
w1 = np.array([[3,-1],[5,2],[3,-1]])

cov1 = np.cov(w1.T)
m1 = np.mean(w1, axis=0)
produtoI = np.dot(cov1,m1)
print("Produto i",produtoI)
print()

#ii) RESPOSTA F
m0 = np.mean(w0, axis=0)
produtoII = np.dot(cov1,m0)
print("ProdutoII", produtoII)

#iii)RESPOSTA F
#iv)RESPOSTA V

Produto i [4.88888889 7.33333333]

ProdutoII [ -7.66666667 -11.5       ]


In [7]:
#Pergunta 2 b) 
#i RESPOSTA V
media = np.dot(m0,m1)
print("Media das classes", media)
print()

#ii RESPOSTA F
norma = lg.norm(m1)
print("Norma",norma)

#iii)RESPOSTA F
#iv)RESPOSTA F

Media das classes -12.833333333333332

Norma 3.6666666666666665


In [11]:
#Pergunta 2 c) 
#i RESPOSTA F
media = np.dot(w1.T,w1)
print("Media das classes")
print(media)
print()

#ii RESPOSTA F
cov0 = np.cov(w0.T)
print("Matrix de cov")
print(cov0)
#iii)RESPOSTA F
#iv)RESPOSTA V

Media das classes
[[43  4]
 [ 4  6]]

Matrix de cov
[[ 1.66666667 -1.33333333]
 [-1.33333333  3.        ]]


In [211]:
fName = 'A45125_Q003_data.p'
D = pickle.load(open(fName,'rb'))

In [212]:
X=D['dados']
y=D['trueClass']
print(D.keys())
print(X.shape)
print(y.shape)

dict_keys(['trueClass', 'dados'])
(2, 1850)
(1850,)


In [213]:
#Pergunta 3 a) 
#i RESPOSTA V
m=np.mean(X[:,y!=4],axis=1)
print(m)

#ii) RESPOSTA F
MC3=np.cov(X[:,y!=4])
print("Matriz de Covariancia")
print(MC3)

#iii)RESPOSTA F
#iv)RESPOSTA F

[1.84112768 1.63571432]
Matriz de Covariancia
[[ 8.03685261  3.13089255]
 [ 3.13089255 11.00146119]]


In [214]:
#Pergunta 3 b)
#i) RESPOSTA V
print("Prioridade apriori de 0: ", (X[:, y==0]).shape[1]/1850)
print()
#ii) RESPOSTA F
MC3=np.cov(X[:,y==2])
print("Matriz de Covariancia")
print(MC3)
#iii)F
#iv)F

Prioridade apriori de 0:  0.1891891891891892

Matriz de Covariancia
[[ 8.66288819e-01 -4.04818712e-03]
 [-4.04818712e-03  4.07768126e+00]]


In [215]:
#Pergunta 3 c)
#i) RESPOSTA V
m0 = np.mean(X[:,y==0],axis=1)
print("Media da classe 0", m0)
print()
#ii) RESPOSTA F
m2 = np.mean(X[:,y==2],axis=1)
print("Media da classe 2", m2)

#iii)F
#iv)F

Media da classe 0 [-1.30702334  3.75049968]

Media da classe 2 [ 1.6433105  -3.80536319]


In [216]:
#Pergunta 3 d)
#i) RESPOSTA V
MC0 = np.cov(X[:,y==0])
mean2 = np.mean(X[:,y==2],axis=1)
produto = np.dot(MC0,mean2)
print("Produto do vetor", produto)
print()
#ii)RESPOSTA F
m0 = np.mean(X[:,y==0],axis=1)
m2 = np.mean(X[:,y==2],axis=1)
produto02 = np.dot(m0.T,m2)
print("produto interno ",produto02)
print()
#iii) RESPOSTA F
m0 = np.mean(X[:,y==0],axis=1)
MC1 = np.cov(X[:,y==1])
m2 = np.mean(X[:,y==2],axis=1)
produtoIII_1 =np.dot(m0.T,MC1)
produtoIII_2 = np.dot(produtoIII_1,m2)
print("Produto matricial ",produtoIII_2)
print()

#iv) RESPOSTA F
MC0 = np.cov(X[:,y==0])
MC3 = np.cov(X[:,y==3])
produtoMC = np.dot(MC0,MC3)
deter = lg.linalg.det(produtoMC)
print("Determinante ", deter)

Produto do vetor [ 1.94238655 -5.02901272]

produto interno  -16.419858627250527

Produto matricial  -14.650716620283685

Determinante  5.2389485389253965
