In [1]:
import numpy as np
import numpy.random as rd
import numpy.linalg as lg
import matplotlib.pyplot as plt
import scipy.spatial.distance as spd
import pickle
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import scipy.spatial.distance as spd
import matplotlib.pyplot as plt

In [2]:
fName='A45125_Q001_data.p'
D=pickle.load(open(fName,'rb'))

In [3]:
X=D['X']
y=D['trueClass']
X1=D['Xtrain'].T
X2=D['Xtest'].T
y1=D['trueClassTrain']
y2=D['trueClassTest']

In [13]:
print(X.shape)
print(X1.shape)
print(X2.shape)
#plt.plot(y1)

(2, 934)
(233, 2)
(701, 2)


In [14]:
#Pergunta 1 a) V F F F
#Pergunta 1 b) F V F F
knn=KNeighborsClassifier(n_neighbors=23).fit(X1,y1)
y2e=knn.predict(X2)
print(np.sum(y2e==y2))
print(confusion_matrix(y2,y2e))

676
[[ 69  10   0   1   0]
 [  2 139   9   0   1]
 [  0   2 120   0   0]
 [  0   0   0 137   0]
 [  0   0   0   0 211]]


In [15]:
fName='A45125_Q003_data.p'
D=pickle.load(open(fName,'rb'))
print(D.keys())

dict_keys(['trueClass', 'estClass'])


In [16]:
ye3 = D['trueClass']
yp3 = D['estClass']
print(ye3.shape)
print(yp3.shape)

(1200,)
(1200,)


In [17]:
#Pergunta 2
w0 = np.array([[1,0],[-1,-1],[1,-3],[-2,0],[-1,-2]])
w1 = np.array([[1,-1],[-2,1],[2,2],[-1,0],[1,-1]])

In [18]:
#Alinea a)

In [19]:
#Alinea b)

In [20]:
#Alinea c)

In [21]:
#Alinea d)
zeros=np.zeros(4)
ones=np.ones(4)
tc=np.hstack((zeros,ones))
print(tc)

[0. 0. 0. 0. 1. 1. 1. 1.]


In [22]:
#Alinea e)
# Alinea A - F V F F
m0=np.mean(w0,axis=0)
m1=np.mean(w1,axis=0)
# i
cov0 = np.cov(w0.T)
cov1 = np.cov(w1.T)
xi=[-4,-2]
Dmi0=spd.mahalanobis(m0,xi,cov0)
Dmi1=spd.mahalanobis(m1,xi,cov1)
print("i")
print("Distancia a m0: ", Dmi0)
print("Distancia a m1: ", Dmi1)

# ii
xii=[-3,2]
Dmii0=spd.mahalanobis(m0,xii,cov0)
Dmii1=spd.mahalanobis(m1,xii,cov1)
print("ii")
print("Distancia a m0: ", Dmii0)
print("Distancia a m1: ", Dmii1)

i
Distancia a m0:  4.578209256903839
Distancia a m1:  7.411612510108715
ii
Distancia a m0:  6.289674077406556
Distancia a m1:  5.80792561935843


In [23]:
#Pergunta 3 a) V F F F
print((771/(771+189))*100)
print(np.sum(ye3==0)/ye3.shape[0])

80.3125
0.8


In [24]:
#Pergunta 3 b) F F F V
taxa = 54/(54+186)
print(taxa)
recall=54/(54+189)
fscore = 2*((taxa*recall)/(taxa+recall))
print("F-Score: ", fscore)

0.225
F-Score:  0.2236024844720497


In [25]:
#Pergunta 3 c) F V F F
print(confusion_matrix(ye3,yp3))

[[771 189]
 [ 54 186]]
